owner: "36570671"
team: "9764292"
lastUpdatedBy: "36570671"
lastRevision: 1781808673000
name: Eschool
color: 180
values:
  - key: urlEschool
    value: https://eschool-api.dev.ol.ge/
    enabled: true
  - key: urlCore
    value: https://eschool-core-api.dev.ol.ge/core/
    enabled: true
  - key: eschoolToken
    value: ""
    enabled: true
  - key: coreToken
    value: ""
    enabled: true
  - key: grant_type
    value: password
    enabled: true
  - key: client_id(Eschool)
    value: eschool
    enabled: true
  - key: client_secret(Eschool)
    value: ""
    enabled: true
  - key: username
    value: ""
    enabled: true
  - key: password
    value: ""
    enabled: true
  - key: eschoolTokenExpiry
    value: "1780492643008"
    enabled: true
  - key: itemId
    value: "1401"
    enabled: true
  - key: coreTokenExpiry
    value: 1780988447202
    enabled: true
  - key: client_id(Core)
    value: core
    enabled: true
  - key: client_secret(Core)
    value: ""
    enabled: true
  - key: lastUpdateDate
    value: '18/05/2026 15:28:55'
  - key: recourceCentersId
    value: "1520"
    enabled: true
  - key: itemLibraryId
    value: "1031"
    enabled: true
  - key: bankName
    value: სს კრედო ბანკი
    enabled: true
  - key: bankCode
    value: "205232238"
    enabled: true
  - key: skipTokenCheck
    value: 'true'
  - key: client_id
    value: ''
  - key: client_secret
    value: ''
color: 180
