name: Eschool
values:
  - key: urlEschool
    value: 'https://eschool-api.dev.ol.ge/'
  - key: urlCore
    value: 'https://eschool-core-api.dev.ol.ge/core/'
  - key: eschoolToken
    value: ''
  - key: coreToken
    value: ''
  - key: grant_type
    value: password
  - key: client_id(Eschool)
    value: eschool
  - key: client_secret(Eschool)
    value: ''
  - key: username
    value: ''
  - key: password
    value: ''
  - key: eschoolTokenExpiry
    value: '1780492643008'
  - key: itemId
    value: '1401'
  - key: coreTokenExpiry
    value: 1780988447202
  - key: client_id(Core)
    value: core
  - key: client_secret(Core)
    value: ''
  - key: lastUpdateDate
    value: '18/05/2026 15:28:55'
  - key: recourceCentersId
    value: '1520'
  - key: itemLibraryId
    value: '1031'
  - key: bankName
    value: სს კრედო ბანკი
  - key: bankCode
    value: '205232238'
  - key: skipTokenCheck
    value: 'true'
  - key: client_id
    value: ''
  - key: client_secret
    value: ''
color: 180
